# Generated by Django 5.1.5 on 2025-10-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnover_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='viz_summary_path',
            field=models.CharField(default='', max_length=500),
        ),
    ]
