# Generated by Django 5.1.5 on 2025-10-20 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnover_app', '0002_analysisresult_viz_summary_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='viz_summary_path',
        ),
    ]
