# Generated by Django 5.1.5 on 2025-10-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnover_app', '0003_remove_analysisresult_viz_summary_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='visualization_path',
            field=models.ImageField(default=1, upload_to='Visualization/'),
            preserve_default=False,
        ),
    ]
