# Generated by Django 5.1.5 on 2025-10-28 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnover_app', '0004_analysisresult_visualization_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='visualization_path',
        ),
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to='turnover_app.analysisresult')),
            ],
        ),
    ]
