# Generated by Django 5.1.5 on 2025-11-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnover_app', '0005_remove_analysisresult_visualization_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='image_path',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Visualization',
        ),
    ]
