# Generated by Django 5.1.5 on 2025-11-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnover_app', '0006_analysisresult_image_path_delete_visualization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='image_path',
            field=models.JSONField(default=list),
        ),
    ]
