# Generated by Django 5.1.5 on 2025-11-02 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnover_app', '0007_alter_analysisresult_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='analysis_images/')),
                ('alt_text', models.CharField(blank=True, max_length=250)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to='turnover_app.analysisresult')),
            ],
        ),
    ]
