# Generated by Django 5.1.5 on 2025-11-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnover_app', '0008_resultimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='image_path',
        ),
    ]
